### ISSUE TITLE
iOS keyboard does not support auto-capitalisation

### ISSUE THREAD

**Issue by bt** [sn-extensions/advanced-markdown-editor#11]
I'm experiencing some issues on iOS where the editor doesn't support the Auto-Capitalization feature.

This is where, when ending the current sentence, the next sentence automatically starts with a capital letter. I sometimes write documentation on the go so having this supported will save me from having to keep pressing the SHIFT key.

Right now, if you have SHIFT pressed, it will stay in caps (as if you had Caps Lock on).

**Comment by atmoio** [comment]
Good point, hadn't noticed this behavior before.

**Comment by bt** [comment]
@mobitar: I think in addition, the spell checker doesn’t work either.

I have fat fingers which gives me quite a hard time typing in this extension unfortunately :(

**Comment by atmoio** [comment]
Yeah, editors on mobile will be a stretch. They're mostly meant for read-only on mobile. They're very complex pieces of software that are meant for a desktop environment.

**Comment by bt** [comment]
Just for reference, this issue has been reported on `SimpleMDE`, which in-turn has been reported on CodeMirror. Here's the relevant issue: https://github.com/codemirror/CodeMirror/issues/3403

**Comment by atmoio** [comment]
Oh wow, quite an old issue. Can't wait for CodeMirror 6 :)

**Comment by bt** [comment]
Hey @mobitar, can we revisit this issue?

There's been some activity in the issue that I mentioned previously; particularly this comment where apparently it was due to the editor having the wrong value set (`false` instead of `off`)

See here: https://github.com/codemirror/CodeMirror/issues/3403#issuecomment-481712134

**Comment by atmoio** [comment]
Thanks for the heads up. I've updated to EasyMDE 2.8.0, which features CodeMirror 5.48.4, which includes the caps fix. Will be deployed in a few minutes. Note that on iOS the surest way to clear editor cache is to uninstall then reinstall the app, or wait for an App Store update.

**Comment by alandooz** [comment]
Based on comments above I think this is fixed thanks to @mobitar updates.
