### ISSUE TITLE
Setting of preview mode should be remembered

### ISSUE THREAD

**Issue by Cito** [sn-extensions/advanced-markdown-editor#12]
When I display a note with the advanced MarkDown editor in preview mode, then visit another note, and then come back to the first note, the setting of the preview mode is not remembered, but always reset to edit mode.

It would be great if the mode in which a note is displayed would be remembered, either for each note individually, or at least globally.

For some notes it is more likely you want to just view them and have formatted headings and nice, clickable hyperlinks, for other notes it is more likely you want to edit them. Therefore it would make sense to store the setting individually per note.

**Comment by atmoio** [comment]
Indeed, would be useful. Will need to look into feasibility.

**Comment by LudwikJaniuk** [comment]
In general, do editors have ways of saving per-note settings?

**Comment by Cito** [comment]
@LudwikJaniuk Maybe this could even be a flag that is not editor specific. The preview/edit mode could also be interesting in other formats/editors like HTML or LaTeX.

We already *have* such flags, like "Pin" , "Archive", "Log" or "Protect". Actually we already a "Preview" flag per note, too, which is a bit confusing because it serves a different purpose, namely showing a preview of the note (the first line of its text) in the note list. Maybe it could then be renamed to "teaser-text" or something, and the feature in question here could be renamed "Edit mode"? It could work exactly like the other flags. Editors that support a preview mode could then make use of that flag. There could also be a global setting for "Edit mode", and one per note, just like it is the case for the current "Preview" (in lsit) mode.

**Comment by LudwikJaniuk** [comment]
That does sound like the best way of implementing such a feature given SN's philosophy. On the other hand, it totally makes no sense when you have no such editors installed...
Also, thinking more broadly about potential editors of the future, it would be an interesting idea to let editors save settings per-note in general. The editors already have global settings, right? What's stopping one of those from being a map from note-ids to custom flags?

**Comment by atmoio** [comment]
Editors can definitely save per-note settings. That's how the Code Editor is able to set a different syntax language per note.

**Comment by LudwikJaniuk** [comment]
Oh great! That's awesome that that already exists

**Comment by atmoio** [comment]
This is now available in 1.3.4 of the editor.

**Comment by Cito** [comment]
Cool, thanks a lot. I can confirm that it works for me after updating. SN is getting better every day!
