### ISSUE TITLE
Syntax highlighting in preview

### ISSUE THREAD

**Issue by rsau** [sn-extensions/advanced-markdown-editor#17]
Advanced Markdown Editor(AME) is based on https://github.com/Ionaru/easy-markdown-editor  which has https://highlightjs.org/ included but it is off by default.   

Syntax gets formatted properly but there is no highlighting by default in AME. 
Is there an option which could be turned on by user along with selection of theme for highlighting?

**Comment by atmoio** [comment]
Not sure. Would have to take a look when I get the chance.

**Comment by rsau** [comment]
> renderingConfig: Adjust settings for parsing the Markdown during previewing (not editing).
codeSyntaxHighlighting: If set to true, will highlight using highlight.js. Defaults to false. To use this feature you must include highlight.js on your page or pass in using the hljs option    

in https://github.com/Ionaru/easy-markdown-editor/blob/master/README.md#options-list

**Comment by atmoio** [comment]
Hmm interesting. If someone can submit a PR for this it will make it much more likely we get it in sooner.
