### ISSUE TITLE
How to add this extension to Standard Notes?

### ISSUE THREAD

**Issue by ttl76543** [sn-extensions/advanced-markdown-editor#32]
Hope I'm asking this in the right place. It's not clear to me from the readme how I can add this extension to Standard Notes using the "Import Extension" function.

**Comment by theodorechu** [comment]
Hello 👋 You can find out here: https://standardnotes.org/help/29/how-do-i-install-extensions-once-i-ve-signed-up-for-extended

**Comment by alandooz** [comment]
Maybe this issue could be close.
