### ISSUE TITLE
Extension on Android

### ISSUE THREAD

**Issue by Jungack** [sn-extensions/advanced-markdown-editor#33]
Hello,
I don't have an extended account yet but am considering for one. Just before, I want to test this extension by self hosting It on my PC. I want to be able to access It on Android. However, when selecting this extension, I'm redirected to the web browser, on the `index.html` of this extension. Is it an extended feature to be able to access extensions on Android, even if they are self hosted?
Thanks !

**Comment by atmoio** [comment]
Make sure there are no trailing slashes in your ext.json hosted_url/url field. The app checks for url equality and if they don't match the editor's url, it's opened in an external browser.

**Comment by Jungack** [comment]
> Make sure there are no trailing slashes in your ext.json hosted_url/url field. The app checks for url equality and if they don't match the editor's url, it's opened in an external browser.

Thank you for this fast answer ! Wow It's working well even on the mobile app ! I needed to put `https://domain.com/path/index.html`. I didn't put the index.html before. Thank you ! I am just testing the simple task extension (I still have some trouble setting It with Nginx) but if I feel well, bye Evernote and welcome Standard Notes ! Thanks again !
