### ISSUE TITLE
Code block text overflow bug

### ISSUE THREAD

**Issue by anavarre** [sn-extensions/advanced-markdown-editor#34]
I hope this is the correct repo to file this bug against. This is for the https://standardnotes.org/extensions/markdown-pro extension.

FYI I tried to reproduce upstream at https://easymde.tk/ and couldn't. See below in Standard Notes:

![markdown-pro-code-block](https://user-images.githubusercontent.com/293478/75033394-19f74e00-54ab-11ea-9d5e-adce0353b14e.png)

The expected behavior would be for the code to be either wrapped to a new line or get the code block box to expand.

**Comment by ningsongshen** [comment]
@anavarre we've fixed the code block issue here: https://github.com/standardnotes/markdown-pro/pull/42. You'll be able to see the code block expand with a scroll bar now!
