### ISSUE TITLE
Toggle Preview doesn't stay

### ISSUE THREAD

**Issue by zevlee** [sn-extensions/advanced-markdown-editor#53]
Ever since the 3.6.8 update, the "Toggle Preview" mode doesn't stay toggled on. This happens both on the desktop and mobile applications.

Steps to reproduce:
1. Toggle Preview off -> on. Wait until all changes are saved.
2. Switch to another note.
3. Switch back to the original note.

The note won't be toggled on when you return to it.

**Comment by JaspalSuri** [comment]
Hi @zevlee, I was able to reproduce this. I will get in touch with our Extensions dev on this to see if there were some changes made recently to the extension that affected the saved states of notes using the Markdown Pro Editor.

**Comment by zevlee** [comment]
From what I've observed, this issue no longer occurs.
