### ISSUE TITLE
Unsafe content alert is overzealous

### ISSUE THREAD

**Issue by ghost** [sn-extensions/advanced-markdown-editor#59]
The new alert which displays when you load a note is overzealous. It will display a warning for any appearance of a less-than followed by a greater-than sign (< >) in a note, irrespective of how they appear in the note.

For example, the following example notes displayed the warning, even when the appearance of these symbols was within a single grave code block.

``` To specify a HTML page title you can use the `<title>` tag. ```

And

``` `<>` ```

This warning can also be reproduced by replacing the single grave with triple grave code blocks.

Please can this be resolved, this makes notes documenting any language using < followed by > display warnings (i.e. I've got a lot of notes about HTML which now all display this warning!). Thanks.

**Comment by JaspalSuri** [comment]
Hi @SciapodousNelipot, sorry for the delayed response. We've made some changes to the internal version of the Markdown Pro Editor and are testing them for the next update. Warnings will not appear for text that is enclosed with back ticks. 🙂

**Comment by johnny243** [comment]
Hi @SciapodousNelipot, this is fixed on the latest version of the Markdown Pro editor (1.3.13)
